import { Toaster } from "@/components/ui/sonner"
import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import Provider from "./_trpc/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="pt-PT">
      <body>
        <Provider>{children}</Provider>
        <Toaster />
        </body>
    </html>
  );
}
